instrumentation:
    verbose: true
    root: lib
    include-all-sources: true
    excludes:
        - '**/*.spec.*.js'
reporting:
    print: summary
    reports:
        - lcov
        - cobertura
    dir: ./coverage/default
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
